name = "BijectiveMorphisms"
uuid = "e5cea73a-f0c5-479d-b77e-c222d88b476b"
version = "0.2.0"
authors = ["P. Phi"]

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
